include:
  - template: Dependency-Scanning.gitlab-ci.yml
#  - template: SAST.gitlab-ci.yml
#  - template: License-Management.gitlab-ci.yml
#  - template: Container-Scanning.gitlab-ci.yml
#
#license_management:
#  stage: test
#  image:
#    name: registry.gitlab.com/widerin/license-management:jdk11
#    entrypoint: [""]
#  variables:
##    SETUP_CMD: ./gradlew --quiet --no-daemon assemble
#    SETUP_CMD: ./mvn package
#  script:
#    - /run.sh analyze .
#  artifacts:
#    reports:
#      license_management: gl-license-management-report.json
#
#sast:
#  image: docker:stable
#  stage: test
#  variables:
#    DOCKER_DRIVER: overlay2
#  services:
#    - docker:stable-dind
#  before_script:
#    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
#  script:
#    - docker run --env SAST_CONFIDENCE_LEVEL="${SAST_CONFIDENCE_LEVEL:-3}"
#      --env SAST_DEFAULT_ANALYZERS=""
#      --env SAST_ANALYZER_IMAGES="registry.gitlab.com/widerin/find-sec-bugs-gradle:jdk11"
#      --volume "$PWD:/code"
#      --volume /var/run/docker.sock:/var/run/docker.sock
#      "registry.gitlab.com/gitlab-org/security-products/sast:$SP_VERSION" /app/bin/run /code
#  artifacts:
#    reports:
#      sast: gl-sast-report.json


image: maven:latest

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode --fail-at-end --show-version"
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"

cache:
  paths:
    - .m2/repository/
    - target/

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS verify
  artifacts:
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml

deploy:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS deploy
  only:
    - master